name: Node CI

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: ESLint checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        uses: gimenete/eslint-action@1.0
